name: MapImg
version: 1.0
api-version: 1.13
main: minestarnetwork.MapImgMain
commands:
  mapimg:
    usage: /<command>
    description: Base MapImg command
  test:
    usage: /<command>
    description: Debug Command